export const categories = [
  { id: 'all', name: 'All Services' },
  { id: 'Online form filling', name: 'Online Form Filling' },
  { id: 'Government forms', name: 'Government Forms' },
  { id: 'Job applications', name: 'Job Applications' },
  { id: 'College/university admission forms', name: 'College Admission' },
  { id: 'Scholarship forms', name: 'Scholarships' },
  { id: 'PAN-related services', name: 'PAN Services' },
  { id: 'Passport-related application assistance', name: 'Passport Assistance' },
  { id: 'Railway/flight/bus booking', name: 'Ticket Booking' },
  { id: 'Document scanning', name: 'Scanning' },
  { id: 'PDF creation/editing', name: 'PDF Editing' },
  { id: 'Printout services', name: 'Printouts' },
  { id: 'Resume/CV making', name: 'Resume / CV' },
  { id: 'Photo/signature resizing', name: 'Photo Resizing' },
  { id: 'Online payment/recharge', name: 'Online Payment' },
  { id: 'Certificate applications', name: 'Certificates' },
  { id: 'Income/caste/residence certificate assistance', name: 'Caste / Income / Domicile' }
];

export const services = [
  {
    id: 'pan-card',
    name: 'PAN Card Application & Correction',
    title: 'PAN Card Application & Correction',
    description: 'New PAN Card (Form 49A), reprint of damaged/lost card, and Aadhaar-PAN linking assistance.',
    category: 'PAN-related services',
    price: 199,
    pricePaise: 19900,
    estimatedTime: '24-48 Hours',
    requiredDocuments: ['Aadhaar Card', 'Passport Size Photo', 'Signature Specimen'],
    icon: 'IdCard'
  },
  {
    id: 'aadhaar-update',
    name: 'Aadhaar Demographic Update',
    title: 'Aadhaar Demographic Update',
    description: 'Assistance for online appointment booking, name/address update documentation, and PVC card order.',
    category: 'Government forms',
    price: 149,
    pricePaise: 14900,
    estimatedTime: '24 Hours',
    requiredDocuments: ['Existing Aadhaar Card', 'Proof of Address (Utility Bill/Bank Passbook)'],
    icon: 'Fingerprint'
  },
  {
    id: 'voter-id',
    name: 'Voter ID Card Registration & Correction',
    title: 'Voter ID Card Registration & Correction',
    description: 'Fresh voter ID registration (Form 6), address shifting (Form 8), and digital e-EPIC download.',
    category: 'Government forms',
    price: 149,
    pricePaise: 14900,
    estimatedTime: '2-3 Working Days',
    requiredDocuments: ['Aadhaar Card', 'Passport Photo', 'Age Proof / Birth Certificate'],
    icon: 'Vote'
  },
  {
    id: 'passport-assistance',
    name: 'Passport Application & Appointment Assistance',
    title: 'Passport Application & Appointment Assistance',
    description: 'Fresh normal/tatkaal passport application, PSK appointment scheduling, and document checklist verification.',
    category: 'Passport-related application assistance',
    price: 699,
    pricePaise: 69900,
    estimatedTime: '3-5 Working Days',
    requiredDocuments: ['Aadhaar Card', 'PAN Card', '10th Marksheet / Birth Certificate', 'Passport Photo'],
    icon: 'Book'
  },
  {
    id: 'income-caste-residence',
    name: 'Income, Caste & Residence Certificates',
    title: 'Income, Caste & Residence Certificates',
    description: 'State revenue portal application for OBC/SC/ST caste certificates, annual income certificate, and domicile.',
    category: 'Income/caste/residence certificate assistance',
    price: 199,
    pricePaise: 19900,
    estimatedTime: '2-4 Working Days',
    requiredDocuments: ['Aadhaar Card', 'Ration Card / Electricity Bill', 'Self Declaration Affidavit', 'Photo'],
    icon: 'FileText'
  },
  {
    id: 'scholarship-forms',
    name: 'National & State Scholarship Form Filling',
    title: 'National & State Scholarship Form Filling',
    description: 'NSP portal, Post-Matric, Pre-Matric, and merit-cum-means scholarship application and document upload.',
    category: 'Scholarship forms',
    price: 249,
    pricePaise: 24900,
    estimatedTime: '24 Hours',
    requiredDocuments: ['Aadhaar Card', 'Income Certificate', 'Previous Marksheet', 'Bank Passbook', 'College Fee Receipt'],
    icon: 'GraduationCap'
  },
  {
    id: 'job-applications',
    name: 'Government & PSU Job Application Filling',
    title: 'Government & PSU Job Application Filling',
    description: 'SSC, UPSC, Railway (RRB), State Police, Banking (IBPS), and Defence online application submission.',
    category: 'Job applications',
    price: 249,
    pricePaise: 24900,
    estimatedTime: '12-24 Hours',
    requiredDocuments: ['Aadhaar Card', 'Educational Marksheets', 'Photo & Signature (Pre-resized)', 'Caste Certificate'],
    icon: 'Briefcase'
  },
  {
    id: 'college-admission',
    name: 'College & University Admission Forms',
    title: 'College & University Admission Forms',
    description: 'UG / PG university entrance registration, centralized counseling portal forms, and admission applications.',
    category: 'College/university admission forms',
    price: 299,
    pricePaise: 29900,
    estimatedTime: '24 Hours',
    requiredDocuments: ['10th & 12th Marksheets', 'Transfer Certificate', 'Aadhaar Card', 'Passport Photo'],
    icon: 'School'
  },
  {
    id: 'travel-ticket-booking',
    name: 'Railway, Flight & Bus Ticket Booking',
    title: 'Railway, Flight & Bus Ticket Booking',
    description: 'Confirmed IRCTC railway tickets, domestic flight booking, and interstate AC sleeper bus reservations.',
    category: 'Railway/flight/bus booking',
    price: 99,
    pricePaise: 9900,
    estimatedTime: '1-2 Hours',
    requiredDocuments: ['Passenger Govt ID details', 'Travel Route & Date'],
    icon: 'Train'
  },
  {
    id: 'document-scanning',
    name: 'High-Resolution Document Scanning & Archival',
    title: 'High-Resolution Document Scanning & Archival',
    description: 'Multi-page document scanning, optical character recognition (OCR), and PDF digitization.',
    category: 'Document scanning',
    price: 49,
    pricePaise: 4900,
    estimatedTime: '30 Minutes',
    requiredDocuments: ['Original Physical Documents'],
    icon: 'Scan'
  },
  {
    id: 'pdf-creation-editing',
    name: 'PDF Creation, Editing & Optimization',
    title: 'PDF Creation, Editing & Optimization',
    description: 'PDF merge, split, watermark, compress to under 100KB for government portals, and format conversions.',
    category: 'PDF creation/editing',
    price: 49,
    pricePaise: 4900,
    estimatedTime: '30 Minutes',
    requiredDocuments: ['Source Files / Photos'],
    icon: 'FileEdit'
  },
  {
    id: 'printout-services',
    name: 'Color & B/W Printout & Lamination',
    title: 'Color & B/W Printout & Lamination',
    description: 'High-speed document printing, admit cards, color photo prints, and protective thermal lamination.',
    category: 'Printout services',
    price: 29,
    pricePaise: 2900,
    estimatedTime: '1 Hour',
    requiredDocuments: ['Document to print (PDF/Image)'],
    icon: 'Printer'
  },
  {
    id: 'resume-cv-making',
    name: 'Professional Resume & CV Making',
    title: 'Professional Resume & CV Making',
    description: 'Modern ATS-friendly resume formatting tailored for job seekers, fresh graduates, and experienced staff.',
    category: 'Resume/CV making',
    price: 249,
    pricePaise: 24900,
    estimatedTime: '24 Hours',
    requiredDocuments: ['Bio-data / Educational & Experience Details'],
    icon: 'FileText'
  },
  {
    id: 'photo-signature-resizing',
    name: 'Photo & Signature Resizing for Portals',
    title: 'Photo & Signature Resizing for Portals',
    description: 'Exact pixel dimensions and KB compression (20KB - 50KB) adhering to strict exam board specifications.',
    category: 'Photo/signature resizing',
    price: 49,
    pricePaise: 4900,
    estimatedTime: '15-30 Minutes',
    requiredDocuments: ['Passport Photo', 'Signature on white paper'],
    icon: 'Crop'
  },
  {
    id: 'utility-bill-payment',
    name: 'Utility Bill Payment & Online Recharges',
    title: 'Utility Bill Payment & Online Recharges',
    description: 'Instant settlement of electricity bills, water bills, FASTag recharge, and property tax payments with receipts.',
    category: 'Online payment/recharge',
    price: 29,
    pricePaise: 2900,
    estimatedTime: '15 Minutes',
    requiredDocuments: ['Consumer Number / Bill Copy'],
    icon: 'CreditCard'
  },
  {
    id: 'birth-death-certificates',
    name: 'Birth, Death & Civil Certificate Applications',
    title: 'Birth, Death & Civil Certificate Applications',
    description: 'Municipal corporation and gram panchayat civil registration assistance and digital certificate issuance.',
    category: 'Certificate applications',
    price: 249,
    pricePaise: 24900,
    estimatedTime: '3-5 Working Days',
    requiredDocuments: ['Hospital Discharge / Event Proof', 'Parents / Spouse Identity Proofs', 'Self Affidavit'],
    icon: 'Award'
  }
];

export const myOrders = [
  { id: '10248', serviceId: 'pan-card', serviceName: 'PAN Card Application & Correction', date: '20 May 2024', amount: 199, status: 'In Progress', worker: { name: 'Amit Cyber Cafe & Digital Seva', rating: 4.9, completedJobs: 134 } },
  { id: '10247', serviceId: 'scholarship-forms', serviceName: 'National & State Scholarship Form Filling', date: '18 May 2024', amount: 249, status: 'Completed', worker: { name: 'Neha Online Documentation Hub', rating: 4.8, completedJobs: 98 } },
  { id: '10246', serviceId: 'aadhaar-update', serviceName: 'Aadhaar Demographic Update', date: '15 May 2024', amount: 149, status: 'Completed', worker: { name: 'Mona E-Services & CSC Center', rating: 4.7, completedJobs: 64 } }
];
